config/routes.rb
Rails.application.routes.draw do

  resources :companies, only: [:new, :create]
  root to: 'jobs#premium'
  resources :jobs do
  post "comments", to: "comments#create"
  end
  delete "comments/:id", to: "comments#destroy", as: :comment
  get 'hello/world'

  get  "/companies/login", to: "login#new"
  post "/companies/login", to: "login#create"
  delete "/companies/login", to: "login#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :job, counter_cache: true
	validates_presence_of :body, :job_id, :name
end

app/models/company.rb
require "bcrypt"

class Company < ActiveRecord::Base
has_many :jobs
  
  def password=(new_password)
    @password = new_password
    self.encrypted_password = BCrypt::Password.create(@password)
  end

  def password
    @password
  end

  def valid_password?(password_to_validate)
  BCrypt::Password.new(encrypted_password) == password_to_validate
  end

validates_presence_of :email, :name, :password
validates_uniqueness_of :email
validates_length_of :password, minimum: 6
validates_confirmation_of :password
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :company
	has_many :comments
 	scope :most_recent, -> {
 		order("created_at DESC")
 		}
 	validates_presence_of :description, :title, :company_id

 	def to_param
 		"#{id}-#{title}"
    end

    def self.find_by_slug(slug)
     result = find(slug)
      if result.to_param == slug
      result
      else
      raise SlugError.new(result)
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_locale

rescue_from SlugError, :with => :rescue_from_slug_error


private
  def rescue_from_slug_error exception
  redirect_to exception.object
  end

  def current_company
    @current_company ||= if session[:company_id]
      Company.find_by_id(session[:company_id])
    end
  end
  helper_method :current_company

  def set_locale
    locale = params[:locale] || cookies[:locale]

    if locale.present?
      I18n.locale = locale
      cookies[:locale] = { value: locale, expires: 30.days.from_now }
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @job = Job.find(params[:job_id])
    @comment = @job.comments.build(params[:comment].permit!)

    respond_to do |format|
      format.html do
        if @comment.save
          flash[:success] = "Comment was created with success!"
        else
          flash[:danger] = "Fill all fields to create a comment."
        end
        redirect_to @job
      end
      format.js do
        @comment.save
      end
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = "Comment was deleted with success!"
    redirect_to @comment.job
  end
end

 

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      flash[:success] = 'Company was successfully created.'
      redirect_to root_path
    else
      flash[:danger] = 'There was a problem creating the Company.'
      render action: "new"
    end
  end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :email, :password, :password_confirmation)
    end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authorize_company, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]


def new_comment(job, comment)
  @job = job
  @comment = comment
  @company = job.company

  mail to: @company.email, subject: "New comment received"
end

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.most_recent.includes(:company).paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  def premium
    @jobs = Job.where(premium: true).most_recent.includes(:company).paginate(page: params[:page], per_page: 10)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
     @job = Job.find_by_slug(params[:id])
     @comments = @job.comments.order('id desc')

     respond_to do |format|
     format.html # show.html.erb
     format.json { render json: @job }
     end
  end

  # GET /jobs/new
  def new
    @job = current_company.jobs.build
  end

  # GET /jobs/1/edit
  def edit
    @job = current_company.jobs.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_company.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        flash[:success] = 'Job was successfully created.'
        format.html { redirect_to @job}
        format.json { render :show, status: :created, location: @job }
      else
        flash[:danger] = 'There was a problem creating the Job.'
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    @job = current_company.jobs.find(params[:id])
    respond_to do |format|
      if @job.update(job_params)
        flash[:success] = 'Job was successfully updated.'
        format.html { redirect_to @job}
        format.json { render :show, status: :ok, location: @job }
      else
        flash[:danger] = 'There was a problem updating the Job.'
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = current_company.jobs.find(params[:id])
    @job.destroy
    respond_to do |format|
      flash[:success] = 'Job was successfully deleted.'
      format.html { redirect_to jobs_url}
      format.json { head :no_content }
    end
  end

  private
    def authorize_company
      unless current_company
        redirect_to root_path
        flash[:danger] = 'You need to login to continue.'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :premium, :comment)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    company = Company.find_by_email(params[:company][:email])

    if company && company.valid_password?(params[:company][:password])
      session[:company_id] = company.id
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid e-mail or password."
      render action: "new"
    end
  end
   
  def destroy
    session.clear
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
	 def job_title(job)
    title = raw("#{h(job.title)} - #{h(job.company.name)}")

    if job.premium
      title + content_tag(:strong, " (premium)")
    else
      title
    end
  end
end

app/views/comments/_comment.html.erb
<h5><strong><%= t ".said", name: comment.name %>:</strong><h5>
<h5><%= simple_format comment.body %><h5>
<h6><i><%= t ".sent", timestamp: time_ago_in_words(comment.created_at) %></i><h6> 
<%= link_to t("links.destroy"), comment_path(comment), method: :delete, confirm: t("links.destroy_confirmation"), class: 'btn btn-danger btn-xs'%>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new], html: { class: 'form-horizontal' }, remote: true do |f| %>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 5 %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/comments/create.js.erb
// create.js.erb

<% if @comment.errors.empty? %>
  $('#comments').prepend('<%=j render(@comment) %>');
  $('#new_comment')[0].reset();
  alert('Comment was created with success!');
<% else %>
  alert('Please fill in all fields to create a comment.');
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: 'form-horizontal' }) do |f| %>
  <% if @company.errors.any? %>
    <div class="alert alert-error">
      <h3><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/new.html.erb
<h3>New company</h3>

<%= render 'form' %>

<%= link_to 'Back', request.referer %>

app/views/hello/world.html.erb
<h1>Hello world</h1>
<strong><%= Time.now %></strong>

app/views/jobs/_form.html.erb
<%= form_for(@job, html: {class: 'form-horizontal'}) do |f| %>
  <% if @job.errors.any? %>
    <div class="alert alert-error">
      <h3><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h3>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.label :premium, class: 'checkbox' do %>
        <%= f.check_box :premium, rows: 10 %> Premium
      <% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, rows: 10 %>
    </div>
  </div>

  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/jobs/_job.html.erb
<table class="table">

<h3><%= job_title(job) %></h3>

<%= simple_format job.description %>

</table>

<p>
  <%= pluralize(job.comments.size, "comment") %>
  <%= link_to 'Show', job, class: 'btn btn-primary btn-xs' %> 
  <% if current_company == job.company %>
  <%= link_to 'Edit', edit_job_path(job), class: 'btn btn-info btn-xs' %> 
  <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
  <% end %>
</p>

app/views/jobs/_premium.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View Premium jobs', root_path %></li>
  <li class="active"><%= link_to 'View all jobs', jobs_path %></li>
  <li><%= link_to new_job_path, class: 'btn btn-success' do %>
<i class="glyphicon glyphicon-plus"></i> New Job
<% end %></li>
</ul>


<%= render @jobs %>

<%= will_paginate @jobs %>

<br />
<%= link_to 'Hello World', hello_world_path %>
<br>
<%= link_to 'Premium jobs', root_path %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= render 'premium' %>

app/views/jobs/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View Jobs', jobs_path %></li>
  <li class="active"><%= link_to 'New Job', new_job_path %></li>
</ul>

<h3>New Job</h3>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<%= render 'premium' %>

app/views/jobs/show.html.erb
<h2><%= job_title(@job) %></h2>

<%= simple_format @job.description %>

<p>
  <%= pluralize(@job.comments.size, t("comments.count")) %> |
  <% if current_company == @job.company %>
    <%= link_to t("links.edit"), edit_job_path(@job) %> |
  <% end %>
  <%= link_to t("links.back"), jobs_path %>
</p>

<h2><%= t ".new_comment" %></h2>
<%= render "comments/form" %>

<h2><%= t ".comments" %></h2>
<div id="comments">
  <%= render @job.comments %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>JobBoard</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'shared/navigation' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3">
          
        </div>
        <div class="col-xs-9">

  <%= yield %>
</div>
      </div>
    </div>

  </body>
</html>

app/views/login/_form.html.erb
<%= form_for(Company.new, url: companies_login_path, html: { class: 'form-horizontal' }) do |f| %>
    <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit "Login", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/login/new.html.erb
<h3>Company login</h3>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Job Ruby App</a>
      <ul class="nav navbar-nav">
          <li><%= link_to "English", locale: "en" %></li>
          <li><%= link_to "Português", locale: "pt-BR" %></li>
        </ul>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul id="app-menu" class="nav navbar-nav navbar-right">
      <li class="active">
          <% if current_company %>
            <li><a><%= t("menu.logged_as") %> <%= current_company.name %></a></li>
            <li><%= link_to t("menu.premium_jobs"), root_path %></li>
            <li><%= link_to t("menu.all_jobs"), jobs_path %></li>
            <li><%= link_to t("menu.new_job"), new_job_path %></li>
            <li><%= link_to t("menu.logout"), companies_login_path, method: :delete, confirm: "Are you sure?" %></li>
          <% else %>
            <li><%= link_to t("menu.login"), companies_login_path %></li>
            <li><%= link_to t("menu.new_company"), new_company_path %></li>
            <li><%= link_to t("menu.premium_jobs"), root_path %></li>
            <li><%= link_to t("menu.all_jobs"), jobs_path %></li>
            <li><%= link_to t("menu.hello_world"), hello_world_path %></li>                
      <% end %>
    </ul>
  </div>
</nav>